#include "../../../version.h"
#if (defined(BACKPROP_TOOLS_DISABLE_INCLUDE_GUARDS) || !defined(BACKPROP_TOOLS_RL_ENVIRONMENTS_MULTIROTOR_OPERATIONS_CPU_H)) && (BACKPROP_TOOLS_USE_THIS_VERSION == 1)
#pragma once
#define BACKPROP_TOOLS_RL_ENVIRONMENTS_MULTIROTOR_OPERATIONS_CPU_H

#include "operations_generic.h"

#include <random>
BACKPROP_TOOLS_NAMESPACE_WRAPPER_START
namespace backprop_tools{
}
BACKPROP_TOOLS_NAMESPACE_WRAPPER_END
#endif
